name: Java CI with Maven + JaCoCo

on:
  push:
    branches:
      - master
      - feature/update-ci
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Common Build & Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build, Unit + Integration Tests
        run: mvn clean verify

  master-build:
    name: Master Branch Job
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Upload JaCoCo report (Master)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-master
          path: target/site/jacoco

  feature-build:
    name: Feature Branch Job
    needs: build
    if: github.ref == 'refs/heads/feature/update-ci'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Upload JaCoCo report (Feature)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-feature
          path: target/site/jacoco
